#hasCJKLanguage = true
languageCode = "en"
disableKinds = ['taxonomy', 'term']
theme = "identity"
copyright = "2023 Profile JP"

baseURL = "https://sample.profile.jp.net"
title = "Profile JP Sample"

[params]
author = "Jane Doe"
icon = "avatar"
description = "CONGUE PELLENTESQUE ELEIFEND"

[[params.social]]
name = "twitter"
icon = "brands fa-twitter"
url = "https://twitter.com/"

[[params.social]]
name = "instagram"
icon = "brands fa-instagram"
url = "https://www.instagram.com/"

[[params.social]]
name = "facebook"
icon = "brands fa-facebook"
url = "https://www.facebook.com/"
